# Generated by Django 2.2.16 on 2022-11-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221121_0224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Катеогория произведения', 'verbose_name_plural': 'Катеогории произведений'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterModelOptions(
            name='titlegenre',
            options={'verbose_name': 'Жанр произведения', 'verbose_name_plural': 'Жанры произведения'},
        ),
    ]
