# Generated by Django 2.2.16 on 2022-11-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221123_2007'),
        ('reviews', '0004_auto_20221123_2319'),
    ]

    operations = [
    ]
