# Generated by Django 2.2.16 on 2022-11-25 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20221125_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2022, message='Нельзя добавлять произведения,которые еще не вышли')], verbose_name='Дата публикации'),
        ),
    ]
